
spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: junyeong237 #? ???? ???? google ??
    password: lyoq dhxy qyhv yzpm #???? ? ????
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always
      continue-on-error: true
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

cloud:
  aws:
    s3:
      bucket: myposts3
    credentials:
      access-key: AKIAVNRLFCIUENTSDREX
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false